# Written by Stuart Kirk
# stuart.kirk@microsoft.com
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT
# NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
# IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
# WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
# SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

- name: Deploy Adaptive Infrastructure Virtual Machine 1
  hosts: localhost
  connection: local
  vars:
       adaptive_rg: 'adaptive1-rg'
       adaptive_host_name: 'adaptive1'
       adaptive_tld: 'adaptivebiotech.com'
       admin_user: 'adaptive'
       azure_dc_location: 'westcentralus'

  tasks:
  - name: Make sure resource group is empty
    azure_rm_resourcegroup:
      name: '{{ adaptive_rg }}'
      location: '{{ azure_dc_location }}'
      force: yes
      state: absent

  - name: Create new resource group
    azure_rm_resourcegroup:
      name: '{{ adaptive_rg }}'
      location: '{{ azure_dc_location }}'

  - name: Create VNet for Adaptive1
    azure_rm_virtualnetwork:
      resource_group: '{{ adaptive_rg }}'
      name: '{{ adaptive_host_name }}-vnet'
      address_prefixes: "10.10.0.0/16"

  - name: Create Subnet for Adaptive1
    azure_rm_subnet:
      resource_group: '{{ adaptive_rg }}'
      name: '{{ adaptive_host_name }}-subnet'
      address_prefix: '10.10.0.0/24'
      virtual_network: '{{ adaptive_host_name }}-vnet'

  - name: Create VM Public IP Address for Adaptive1
    azure_rm_publicipaddress:
      resource_group: '{{ adaptive_rg }}'
      name: '{{ adaptive_host_name }}-pip'
      allocation_method: Static
      domain_name: '{{ adaptive_host_name }}'

  - name: Create NSG for Adaptive1
    azure_rm_securitygroup:
      resource_group: '{{ adaptive_rg }}'
      name: '{{ adaptive_host_name }}-nsg'
      rules:
          - name: 'AllowSSH'
            access: Allow
            destination_port_range: 22
            direction: Inbound
            priority: 1011
            protocol: Tcp

  - name: Create Server VM NIC for Adaptive1
    azure_rm_networkinterface:
      name: '{{ adaptive_host_name }}-nic'
      os_type: Linux
      public_ip_address_name: '{{ adaptive_host_name }}-pip'
      resource_group: '{{ adaptive_rg }}'
      security_group_name: '{{ adaptive_host_name }}-nsg'
      subnet_name: '{{ adaptive_host_name }}-subnet'
      virtual_network_name: '{{ adaptive_host_name }}-vnet'

  - name: Create Server VM Adaptive1
    azure_rm_virtualmachine:
      admin_username: "{{ admin_user }}"
      location: '{{ azure_dc_location }}'
      managed_disk_type: Standard_LRS
      name: '{{ adaptive_host_name }}-vm.{{ adaptive_tld }}'
      network_interface_names: '{{ adaptive_host_name }}-nic'
      os_type: Linux
      resource_group: '{{ adaptive_rg }}'
      short_hostname: '{{ adaptive_host_name }}-vm'
      vm_size: Standard_DS3_v2
      ssh_password_enabled: false
      ssh_public_keys:
        - path: /home/adaptive/.ssh/authorized_keys
          key_data: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
      image:
        offer: CentOS-LVM
        publisher: OpenLogic
        sku: '7-LVM'
        version: 7.5.20180823
      data_disks:
        - lun: 0
          disk_size_gb: 100
          managed_disk_type: Standard_LRS

  - name: Examining Public IP Address Facts
    azure_rm_publicipaddress_facts:
      resource_group: '{{ adaptive_rg }}'
      name: '{{ adaptive_host_name }}-pip'
    register: pipoutput

  - name: Dump FQDN
    debug:
      msg: "FQDN: {{ pipoutput.ansible_facts.azure_publicipaddresses[0].properties.dnsSettings.fqdn }}"
