- name: Deploy Adaptive Infrastructure Virtual Machine 2
  hosts: localhost
  connection: local
  vars:
       adaptive_rg: 'adaptive2-rg'
       adaptive_host_name: 'adaptive2'
       adaptive_tld: 'adaptivebiotech.com'
       admin_user: 'adaptive'
       azure_dc_location: 'westcentralus'
       master_vnet_name: 'adaptive1-vnet'
       master_vnet_rg: 'adaptive1-rg'
       subnet_range: '10.10.1.0/24'

  tasks:

  - name: Make sure resource group is empty
    azure_rm_resourcegroup:
      name: '{{ adaptive_rg }}'
      location: '{{ azure_dc_location }}'
      force: yes
      state: absent

  - name: Create new resource group
    azure_rm_resourcegroup:
      name: '{{ adaptive_rg }}'
      location: '{{ azure_dc_location }}'

  - name: Get facts for Adaptive1 Master VNet
    azure_rm_virtualnetwork_facts:
      resource_group: "{{ master_vnet_rg }}"
      name: '{{ master_vnet_name }}'
    register: facts
  - debug:
      msg: 'Adaptive1 VNet: {{ facts.ansible_facts.azure_virtualnetworks[0].properties.addressSpace.addressPrefixes[0]}}'
  - debug:
      msg: 'Adaptive1 VNet Resource ID: {{ facts.ansible_facts.azure_virtualnetworks[0].id }}'

  - name: Verify Subnet for Adaptive2 exists in Adaptive1 VNet
    azure_rm_subnet:
      resource_group: '{{ master_vnet_rg }}'
      name: '{{ adaptive_host_name }}-subnet'
      address_prefix: '{{ subnet_range }}'
      virtual_network: '{{ master_vnet_name }}'
      state: 'present'

  - name: Create VM Public IP Address for Adaptive2
    azure_rm_publicipaddress:
      resource_group: '{{ adaptive_rg }}'
      name: '{{ adaptive_host_name }}-pip'
      allocation_method: Static
      domain_name: '{{ adaptive_host_name }}'

  - name: Create NSG for Adaptive2
    azure_rm_securitygroup:
      resource_group: '{{ adaptive_rg }}'
      name: '{{ adaptive_host_name }}-nsg'
      rules:
          - name: 'AllowSSH'
            access: Allow
            destination_port_range: 22
            direction: Inbound
            priority: 1011
            protocol: Tcp

  - name: Create Server VM NIC for Adaptive2
    azure_rm_networkinterface:
      name: '{{ adaptive_host_name }}-nic'
      os_type: Linux
      public_ip_address_name: '{{ adaptive_host_name }}-pip'
      resource_group: '{{ adaptive_rg }}'
      security_group_name: '{{ adaptive_host_name }}-nsg'
      subnet_name: '{{ adaptive_host_name }}-subnet'
      virtual_network_name: '{{ facts.ansible_facts.azure_virtualnetworks[0].id }}'

  - name: Create Server VM Adaptive2
    azure_rm_virtualmachine:
      admin_username: "{{ admin_user }}"
      location: '{{ azure_dc_location }}'
      managed_disk_type: Standard_LRS
      name: '{{ adaptive_host_name }}-vm.{{ adaptive_tld }}'
      network_interface_names: '{{ adaptive_host_name }}-nic'
      os_type: Linux
      resource_group: '{{ adaptive_rg }}'
      short_hostname: '{{ adaptive_host_name }}-vm'
      vm_size: Standard_DS3_v2
      ssh_password_enabled: false
      ssh_public_keys:
        - path: /home/adaptive/.ssh/authorized_keys
          key_data: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
      image:
        offer: CentOS-LVM
        publisher: OpenLogic
        sku: '7-LVM'
        version: 7.5.20180823
      data_disks:
        - lun: 0
          disk_size_gb: 100
          managed_disk_type: Standard_LRS

  - name: Examining Public IP Address Facts
    azure_rm_publicipaddress_facts:
      resource_group: '{{ adaptive_rg }}'
      name: '{{ adaptive_host_name }}-pip'
    register: pipoutput

  - name: Dump FQDN
    debug:
      msg: "FQDN: {{ pipoutput.ansible_facts.azure_publicipaddresses[0].properties.dnsSettings.fqdn }}"
